// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxZU7GSXboLVCCawwLedQKJWJY_9oeMzc',
    appId: '1:220079105147:web:928a0540ac0ad7b688eede',
    messagingSenderId: '220079105147',
    projectId: 'smarthomeapp-b9fe6',
    authDomain: 'smarthomeapp-b9fe6.firebaseapp.com',
    storageBucket: 'smarthomeapp-b9fe6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc33dutBNpinWKib0Kp0QGQJhdXIIQBcc',
    appId: '1:220079105147:android:97bd5e9d1bfd441088eede',
    messagingSenderId: '220079105147',
    projectId: 'smarthomeapp-b9fe6',
    storageBucket: 'smarthomeapp-b9fe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPkSj43K2qhjbyF4EUHlEM0CwHvaxONMw',
    appId: '1:220079105147:ios:4d5457df108ea40788eede',
    messagingSenderId: '220079105147',
    projectId: 'smarthomeapp-b9fe6',
    storageBucket: 'smarthomeapp-b9fe6.appspot.com',
    iosBundleId: 'com.example.doanMonhoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPkSj43K2qhjbyF4EUHlEM0CwHvaxONMw',
    appId: '1:220079105147:ios:4d5457df108ea40788eede',
    messagingSenderId: '220079105147',
    projectId: 'smarthomeapp-b9fe6',
    storageBucket: 'smarthomeapp-b9fe6.appspot.com',
    iosBundleId: 'com.example.doanMonhoc',
  );
}
